### ISSUE TITLE
new task priority sent to api is reverse of how it appears in app

### ISSUE THREAD

**Issue by deanmalmgren** [Doist/todoist-python#18]
When I'm in the todoist app and I set `p1` on a task, this is the highest priority that I can set, but when you send something through the API, this is actually [the "natural" state of the priority](https://developer.todoist.com/#add-an-item) (what displays as `p4` in the app). In other words, the scales are reversed between the app and the API.

It would be nice if the priority that is sent to the API was consistent with how it appears in the app. I'm not sure the best way to address this, but I thought I'd share some feedback in case theres a natural solution.

**Comment by lefcha** [comment]
That is correct; `priority 1` on the Web app becomes `4` on the server and thus that's what the you see when using the API.  I think it might be because 4 is the biggest number, and thus programmatically it makes sense to have it this way, but for the end user it makes more sense that `priority 1` is the highest of all.

It's a peculiarity of our API, similar to `notes` and `comments` or `tasks` and `items`, which are different terms used for the same thing, in the clients and in our API.

Unfortunately I am not aware of any plans to change that, although from time to time we fix some inconsistencies such as this.

But in general changing these kind of things might have unexpected results or cause disruptions to the end users, while they don't offer much value to them, so it's kind of logical to not put a high priority on them.
