### ISSUE TITLE
api.sync() returns HTML code for Bad Gateway

### ISSUE THREAD

**Issue by alexandrosio** [Doist/todoist-python#32]
I'm building a project that syncs a service with Todoist; thus, I have to call the `api.sync()` function every 2 seconds or so, taking into account the maximum number of 50 sync requests per minute, to keep the services in sync. Further, by reading your API Documentation, I've assumed the function returns JSON objects only; yet, the result of the `api.sync()` function has returned, on numerous occasions, the HTML code for Error 502 (Bad Gateway).

Please find attached the HTML document below:
[todoist_api_sync_response_error.txt](https://github.com/Doist/todoist-api/files/1261998/todoist_api_sync_response_error.txt)

Regards,
Alexandros

**Comment by PotHix** [comment]
> I've assumed the function returns JSON objects only

We can't assure that all requests will return JSON, although we do that by design and try to return JSON whenever possible.
When we have a 502, the request is served by our shared frontends, not our backend code, and it may use a different content-type.

I would recommend you to always check the content-type returned.
