### ISSUE TITLE
Encrypt cached data

### ISSUE THREAD

**Issue by kalafut** [Doist/todoist-python#38]
In an enterprise environment where, by policy, no data is personal, IT processes often vacuum up and monitor all data on the device.  The sync cache in `~/.todoist-sync/` is plaintext and may have a lot of personal information that the user doesn't realize is potentially accessible.  Encrypting this would be desirable, perhaps using a key derived from the login credentials.

The [Cryptography](https://cryptography.io) library is a safe choice but introduces dependencies, including native C. Vendoring another, pure python implementation is another option.

**Comment by seliger** [comment]
I recently wrote a blog post on how I monkey patched the Python library to use Redis rather than files on a file system. One could concieveably monkey patch the same read and write calls to implement some encryption scheme. 

I've not put in a separate issue, but I did make note that it would be useful to abstract out the caching mechanism so it can be more modular. Using Redis is one valid use case, encrypting the local cache is yet another argument for it. 

This doesn't solve the problem by any stretch, but it should at least give you an opportunity to work around the problem in a way that wouldn't completely break the library.

https://coreyseliger.me/2017/12/03/Using-Redis-to-Cache-the-Todoist-Python-API/

**Comment by PotHix** [comment]
We prefer to not add an external dependency to handle this for everyone. We recommend people in a constrained environment to encrypt `~/.todoist-sync/` in a different way.

If there's a simple issue without adding a hard dependency as `cryptography`, a PR would be welcome. 

I will close this issue. :+1:
