### ISSUE TITLE
Constantly running full syncs

### ISSUE THREAD

**Issue by ccarterlandis** [Doist/todoist-python#50]
Every time I try to sync, it runs a full sync and pulls down all my data, even for entities that haven't been changed. Running this code: 
```
from todoist.api import TodoistAPI
api = TodoistAPI('api_token')
updated_tasks = api.sync()['items']
print(updated_tasks)
```
will print **all** of my currently active tasks, regardless of which tasks I've actually changed in Todoist.

As per [the documentation](https://developer.todoist.com/sync/v7/?python#read-resources), I would expect this to only be returning incremental syncs, and indeed I've been able to achieve this behavior before; however, sudedenly (read: without me changing anything), the API started only returning full syncs, regardless of how many times I run the above code.

Versions:
macOS Mojave: v10.14.2
Python: v3.6.3
todoist-python library: v7.0.19

**Comment by ccarterlandis** [comment]
This problem has slightly evolved. It no longer **constantly** runs full syncs, but only sometimes. Other times, it won't recognize any new changes at all; e.g. if I archive a task, it'll pick up on the change, and then running the code shown above over and over and over again will just show the task as having _just_ been archived.

**Comment by PotHix** [comment]
This should be resolved after the refactoring for the v8 API done some time ago, sorry for not updating.

It's still possible that you're seeing more items coming in the partial sync when only one was updated. It's happening because we're transitioning to v8 of the API, but it will be back to normal after August 30th.

I will close this one, please reopen or create a new one if you still have issues.
